language: python
python:
  - 2.7
  - 3.5
  - 3.6
install:
  - pip install ${DJANGO}
  - pip install -r requirements.txt
  - pip install -r optional-requirements.txt

script:  python manage.py test
env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.11,<1.12"
  - DJANGO="Django>=2.0,<2.1"
matrix:
  exclude:
    - python: 2.7
      env: DJANGO="Django>=2.0,<2.1"